apiVersion: v1
kind: Pod
metadata: 
  name: debug-pod
  namespace: roboshop-dev
  labels:
    name : debug-pod
    project: roboshop
spec: 
  containers: 
  - name : debug 
    image : suryatej01/debug:latest
    imagePullPolicy: Always 

