apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-pod
  namespace: roboshop
  labels:
    name: debug-pod
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      name: debug-pod
      project: roboshop

  template:
    metadata:
      labels:
        name: debug-pod
        project: roboshop

    spec:
      containers:
      - name: debug
        image: suryatej01/debug:v2
        imagePullPolicy: IfNotPresent
# spec → template → spec → containers
