apiVersion: v1
kind: Deployment
metadata: 
  name: debug-pod
  namespace: roboshop
  labels:
    name : debug-pod
    project: roboshop
spec: 
  replicaset: 
    replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      name : debug-pod
      project: roboshop
  containers: 
  - name : debug 
    image : suryatej01/debug:latest
    imagePullPolicy: IfNotPresent 

