apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi
  persistentVolumeClaimPolicy: Retain 
  #retain menas dont delete the data,delete means delete data and disk ,recycle means delete the data dont delete the disk
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-06a436adda4f601e3
