apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  accessModes:
  - ReadWriteOnce
  PersistentVolumeClaimPolicy: retain #retain menas dont delete the data,delete means delete data and disk ,recycle means delete the data dont delete the disk
  capacity:
    storage: 15Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-03c604538dd7d2f41
