kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dynamic
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-02fb0ec2f0278661a
  directoryPerms: "700"
  basePath: "/roboshop" # optional
