apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-demo
  namespace: default
spec: 
  containers:
  - name: nginx
    image: nginx 
    volumeMounts:
    - mountpath: /var/log/nginx
      name: nginix-logs
    
  - name: almalinux
    image: almalinux: 9
    - mountPath: /mnt.nginx-log
      name: nginx
    volumeMounts:
      - mountPath: /mnt/nginix-logs

  volumes:
  - name : nginix-logs
    emptyDir:
      sizelimits: 100Mi
