apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    purpose: dp-demo
    project: roboshop
spec:
  replicas: 4
  selector:
    matchLabels:
      purpose: dp-demo-headless-service
      project: roboshop
  template:
    metadata:
      labels:
        purpose: dp-demo-headless-service
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec:
  clusterIP: None
  selector:
    purpose: dp-demo-headless-service
    project: roboshop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80