apiVersion: v1
kind: Pod 
metadata:
  name: nginx-pod
  labels: 
    project: roboshop
    component: frontend
    environment: dev
    purpose: load-balancer
spec:
  containers:
  - name: nginx-container
    image: nginx:latest

     
        