apiVersion: v1
kind: Pod 
metadata:
  name: nginx-pod
  namespace : roboshop
  labels:
    app: nginx
    labels: 
      project: roboshop
      component: frontend
      environment: dev
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
      - containerPort: 80
    resources:
      requests:
          cpu: "50m"
          memory: "68Mi"
      limits:
          cpu: 100m
          memory: "128Mi"
    env :
    - name: course
      value: "120hours"
     
        