apiVersion: v1
kind: Pod 
metadata:
  name: nginx-pod
  labels:
    app: nginx
    labels: 
      project: roboshop
      component: frontend
      environment: dev
spec:
  containers:
  - name: nginx-container
    image: nginx:latest

     
        