apiVersion: v1
kind: Pod 
metadata:
  labels: 
    name: nginx-pod
    project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx-container
    image: nginx:latest

     
        