apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: rb-dev
  labels:
  # these are replica set lebels
    project: roboshop
    component: mongodb
    tier: db
spec: 
  replicas: 1
  selector:
  # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db 
    spec:
      containers:
      - name: mongodb
        image: suryatej01/mongodb
