apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop-dev
  region: us-east-2

managedNodeGroups:
  - name: roboshop-dev
    instanceType: t3.small
    desiredCapacity: 3
    spot: false
